### PR TITLE
minor changes to mod loading, add setting for running own tests

### PR DESCRIPTION
**Pull request by FluffierThanThou**
As the title says, I added a setting for suppressing RimTests' own suite of tests.
Also changed to a more standard mod loading mechanism in the process, as the Mod class was needed anyway for hooking up settings. Added a button to re-run tests as well.

### CODE REVIEW

**Comment by helldragger** [comment]
Oh that's a nice addition
The only thing you will have to modify to adapt your merge request to the latest version will be to modify the RimTestMod refactored in the Core folder to add the settings panel, and to add the blacklisting to the Explorer.cs (in the Testing folder) instead of RimTest.cs

**Comment by helldragger** [comment]
Currently integrating your changes plus working on an actual interface thanks to your mod setting GUI working example. Everything is hooked up, currently bashing my head on how to actually place things where I want them...

**Comment by FluffierThanThou** [comment]
nice. I don't really have a lot of time at the moment, but I was planning
on contributing a UI at some point in the future. Feel free to ask me
questions on Discrod, RimWorld UI is kind of what most of my mods are about
;).

**Comment by helldragger** [comment]
Yeah UI is kinda my pet peeve... here's the current state of the GUI if you're curious (the controls are the latest additions I just wired up, I'll place them where I want them later) 
image

this is the current design idea: 
image

Do you know how to add a GUI to the debug toolbar though? I tried replicating the huglibs way but transpilers are totally outside of my water... Couldn't get it to work at all

**Comment by helldragger** [comment]
closing the merge request since the interface development has been continued further

**Pull request closed without merging**
